# Generated by Django 4.1.10 on 2023-07-26 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes_users',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
