# Generated by Django 4.1.10 on 2023-07-30 19:08

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_blogpost_likes_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='photo',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='post_media/', validators=[home.models.validate_media_type]),
        ),
    ]
