# Generated by Django 4.2.3 on 2023-08-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_customuser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_active_status',
            field=models.BooleanField(default=True),
        ),
    ]
