# Generated by Django 4.2.3 on 2023-08-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_customuser_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
