# Generated by Django 4.2.3 on 2023-08-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_verificationplan_verificationbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified_badge',
            field=models.BooleanField(default=False),
        ),
    ]
