# Generated by Django 4.2.3 on 2023-08-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_customuser_verified_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationbadge',
            name='verification_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
