# Generated by Django 4.2.3 on 2023-08-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_customuser_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(default='Regular Transaction', max_length=200),
        ),
    ]
