# Generated by Django 4.2.3 on 2023-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_notification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_seen_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
