# Generated by Django 4.2.3 on 2023-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='owned_coupons',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
